# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cipsmodle.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(10, 0, 776, 533))
        self.frame_2.setMinimumSize(QtCore.QSize(776, 533))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 339, 411))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setGeometry(QtCore.QRect(13, 30, 311, 371))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(20, -190, 26, 413))
        self.label.setObjectName("label")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 3)
        self.pushButton_savefile = QtWidgets.QPushButton(self.frame)
        self.pushButton_savefile.setObjectName("pushButton_savefile")
        self.gridLayout.addWidget(self.pushButton_savefile, 4, 2, 1, 1)
        self.pushButton_analys = QtWidgets.QPushButton(self.frame)
        self.pushButton_analys.setObjectName("pushButton_analys")
        self.gridLayout.addWidget(self.pushButton_analys, 1, 0, 1, 3)
        self.pushButton_savefileelse = QtWidgets.QPushButton(self.frame)
        self.pushButton_savefileelse.setObjectName("pushButton_savefileelse")
        self.gridLayout.addWidget(self.pushButton_savefileelse, 4, 1, 1, 1)
        self.pussbutton_openfiles = QtWidgets.QPushButton(self.frame)
        self.pussbutton_openfiles.setObjectName("pussbutton_openfiles")
        self.gridLayout.addWidget(self.pussbutton_openfiles, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.label_2.setObjectName("label_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_3)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 30, 351, 451))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 349, 449))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 10, 341, 431))
        self.textEdit_2.setObjectName("textEdit_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.frame_3, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(20, 10, 681, 471))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(370, 20, 284, 421))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frame_5)
        self.scrollArea_3.setGeometry(QtCore.QRect(10, 40, 261, 361))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 259, 359))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.textEdit_3 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_3)
        self.textEdit_3.setGeometry(QtCore.QRect(0, 0, 261, 361))
        self.textEdit_3.setObjectName("textEdit_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(14, 14, 51, 16))
        self.label_3.setObjectName("label_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setGeometry(QtCore.QRect(10, 20, 341, 421))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_6)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 0, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_2, 1, 1, 1, 2)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 2, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 3, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 4, 0, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 4, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 5, 0, 1, 2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 5, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 6, 0, 1, 2)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_3, 6, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 7, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 8, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 8, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_6)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 9, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 9, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 10, 0, 1, 3)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_4, 7, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widget = QtWidgets.QWidget(self.tab_3)
        self.widget.setGeometry(QtCore.QRect(60, 40, 271, 421))
        self.widget.setObjectName("widget")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.actioncips = QtWidgets.QAction(MainWindow)
        self.actioncips.setObjectName("actioncips")
        self.actiontype_here = QtWidgets.QAction(MainWindow)
        self.actiontype_here.setObjectName("actiontype_here")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "报文"))
        self.pushButton_savefile.setText(_translate("MainWindow", "保存文件"))
        self.pushButton_analys.setText(_translate("MainWindow", "解析报文"))
        self.pushButton_savefileelse.setText(_translate("MainWindow", "另存为"))
        self.pussbutton_openfiles.setText(_translate("MainWindow", "打开文件"))
        self.label_2.setText(_translate("MainWindow", "解析结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "报文解析"))
        self.label_3.setText(_translate("MainWindow", "cips.801"))
        self.label_4.setText(_translate("MainWindow", "分行"))
        self.comboBox.setItemText(0, _translate("MainWindow", "工行总行"))
        self.comboBox.setItemText(1, _translate("MainWindow", "工银亚洲"))
        self.comboBox.setItemText(2, _translate("MainWindow", "工银新加坡"))
        self.label_5.setText(_translate("MainWindow", "环境"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "流程"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "功能"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "数据中心"))
        self.pushButton_4.setText(_translate("MainWindow", "获取当前状态"))
        self.label_6.setText(_translate("MainWindow", "当前工作日"))
        self.label_7.setText(_translate("MainWindow", "上一工作日"))
        self.label_8.setText(_translate("MainWindow", "下一工作日"))
        self.label_9.setText(_translate("MainWindow", "系统状态"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "CLSD：日间营业准备"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "ACTV：日间处理"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "SUSP：日间业务截止"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "CLSG：场终处理"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "NTAC：夜间处理"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "NTSP：夜间业务截止"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "NTCS：日终"))
        self.label_10.setText(_translate("MainWindow", "后状态"))
        self.label_11.setText(_translate("MainWindow", "期数1"))
        self.label_12.setText(_translate("MainWindow", "期数2"))
        self.pushButton_3.setText(_translate("MainWindow", "生成日切报文"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "CLSD：日间营业准备"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "ACTV：日间处理"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "SUSP：日间业务截止"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "CLSG：场终处理"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "NTAC：夜间处理"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "NTSP：夜间业务截止"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "NTCS：日终"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "日切管理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "未完待续"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "未完待续"))
        self.actioncips.setText(_translate("MainWindow", "cips"))
        self.actiontype_here.setText(_translate("MainWindow", "type here"))

