# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buttonTest.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(30, 30, 311, 441))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_savefile = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_savefile.setObjectName("pushButton_savefile")
        self.gridLayout.addWidget(self.pushButton_savefile, 2, 1, 1, 1)
        self.pushButton_openfile = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_openfile.setObjectName("pushButton_openfile")
        self.gridLayout.addWidget(self.pushButton_openfile, 2, 0, 1, 1)
        self.button_analymes = QtWidgets.QPushButton(self.frame_2)
        self.button_analymes.setObjectName("button_analymes")
        self.gridLayout.addWidget(self.button_analymes, 1, 0, 1, 2)
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(350, -30, 380, 541))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 0, 0, 5, 1)
        self.pushButton_copy = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_copy.setObjectName("pushButton_copy")
        self.gridLayout_2.addWidget(self.pushButton_copy, 3, 1, 1, 1)
        self.pushButton_change = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_change.setObjectName("pushButton_change")
        self.gridLayout_2.addWidget(self.pushButton_change, 4, 1, 1, 1)
        self.pushButton_selfdesign = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_selfdesign.setObjectName("pushButton_selfdesign")
        self.gridLayout_2.addWidget(self.pushButton_selfdesign, 1, 1, 1, 1)
        self.pushButton_paste = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_paste.setObjectName("pushButton_paste")
        self.gridLayout_2.addWidget(self.pushButton_paste, 0, 1, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout_2.addWidget(self.pushButton_clear, 2, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 797, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_clear.clicked.connect(self.textBrowser.clear)
        self.pushButton_copy.clicked.connect(self.textBrowser.copy)
        self.pushButton_paste.clicked.connect(self.textBrowser.paste)
        self.button_analymes.clicked.connect(self.textEdit.copy)
        self.button_analymes.clicked['bool'].connect(self.textBrowser.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "尝试处理"))
        self.pushButton_savefile.setText(_translate("MainWindow", "保存文件"))
        self.pushButton_openfile.setText(_translate("MainWindow", "打开文件"))
        self.button_analymes.setText(_translate("MainWindow", "报文解析"))
        self.pushButton_copy.setText(_translate("MainWindow", "复制"))
        self.pushButton_change.setText(_translate("MainWindow", "更改"))
        self.pushButton_selfdesign.setText(_translate("MainWindow", "自定义"))
        self.pushButton_paste.setText(_translate("MainWindow", "黏贴"))
        self.pushButton_clear.setText(_translate("MainWindow", "清理"))

